target 'machumbub' do
  use_frameworks!

  pod 'Alamofire', '~> 5.4'
  pod 'SwiftSoup', '~> 2.3'
  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'

  target 'machumbubTests' do
    inherit! :search_paths
  end

  target 'machumbubUITests' do
  end

end
